version:  '3'
services:
  db:
      ###postgresql
    image: postgres:alpine
    container_name: postgredb
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "54320:5432"
    volumes:
      - ./docker/postgres-data:/var/lib/postgresql/data
     #### mysql:
    #image: mysql:8.0
    # environment:
    #   MYSQL_ROOT_PASSWORD: root
    #   MYSQL_DATABASE: example
    restart: on-failure
   
  php:
    build:
      context: .
      dockerfile: docker/build-php/Dockerfile
      args:
       - SYMFONY_APP_NAME:${SYMFONY_APP_NAME}
    restart: on-failure
    volumes:
      - './apps/${SYMFONY_APP_NAME}/:/usr/src/symfo-app'
    user: ${LOCAL_USER}  

  nginx:
    image: nginx:1.15.3-alpine
    restart: on-failure
    volumes:
      - './apps/${SYMFONY_APP_NAME}/public/:/usr/src/symfo-app'
      - './docker/build-nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
      ##- './docker/build-nginx/symfo-app.conf:/etc/nginx/conf.d/symfo-app.conf:ro'
    ports:
      - '${NGINX_PORT}:80'    
    depends_on:
      - php
    #adminer for db admin    
  adminer:
    image: adminer
    restart: on-failure
    ports:
      - '${ADMINER_PORT}:8080'
  client:
    ##reactAppAdmin
    build:
      context: .
      dockerfile: docker/build-node/Dockerfile-client-client
    volumes:
      - './apps/${REACT_CLIENT_APP_NAME}/src:/usr/src/client-app/src'
      - './apps/${REACT_CLIENT_APP_NAME}/public:/usr/src/client-app/public'
    ports:
      - '${REACT_CLIENT_PORT}:3000'
  admin:
    ##reactAppAdmin
    build:
      context: .
      dockerfile: docker/build-node/Dockerfile-client-admin
    volumes:
      - './apps/${REACT_APP_NAME}/src:/usr/src/admin-app/src'
      - './apps/${REACT_APP_NAME}/public:/usr/src/admin-app/public'
    ports:
      - '${REACT_PORT}:3000'