FROM node:12-alpine

ARG REACT_CLIENT_APP_NAME
# set working directory
WORKDIR /usr/src/client-app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /usr/src/client-app/node_modules/.bin:$PATH
COPY apps/$REACT_APP_NAME /usr/src/client-app
# install and cache app dependencies
COPY package.json /app/package.json
RUN npm install --silent
RUN npm install react-scripts@3.0.1 -g --silent

# start app
CMD ["npm", "start"]