FROM node:12-alpine

ARG REACT_CLIENT_APP_NAME
# set working directory
WORKDIR /usr/src/client-app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /usr/src/client-app/node_modules/.bin:$PATH
COPY apps/client-app /usr/src/client-app
# install and cache app dependencies
RUN npm install --silent
RUN npm install react-scripts -g --silent
RUN npm install bootstrap jquery typescript popper.js @popperjs/core

# start app
CMD ["npm", "start"]
